# 线性代数

In [4]:
import torch

#### 1. 标量

In [5]:
x = torch.tensor([1.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([3.]), tensor([2.]), tensor([0.5000]), tensor([1.]))

#### 2. 向量

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [7]:
x[1]

tensor(1)

#### 3. 张量的长度以及张量的形状

In [10]:
len(x),x.shape

(4, torch.Size([4]))

#### 4. 通过指定两个分量m和n来创建一个形状为m x n的矩阵

In [12]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

#### 5. 矩阵的转置

In [15]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

#### 6.创建对称矩阵，性质为: $A = A^T$

In [18]:
B = torch.tensor([[1, 2, 3], [2, 4, 5], [3, 5, 1]])
B

tensor([[1, 2, 3],
        [2, 4, 5],
        [3, 5, 1]])

In [19]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### 7. m x n的矩阵可以看作是m个n维行向量或n个m维列向量，即矩阵是向量的推广。
#### 而k个矩阵还可能组合起来进行推广

In [20]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

#### 8.给定具有相同形状的任何两个向量，任何按元素二元运算的结果都会得到相同形状的结果

In [25]:
A = torch.arange(20, dtype = torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

#### 9.两个矩阵按元素乘法被称为 哈达玛积（数学符号为：$\odot$）

In [26]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [30]:
a = 2
X = torch.arange(20).reshape(5, 4)
X, a + X, a * X, (a * X).shape # a + X表示对X的所有元素均加上a这个标量

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]),
 torch.Size([5, 4]))

#### 10. 计算元素和

In [31]:
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [32]:
x = torch.arange(40).reshape(2, 5, 4)
x, x.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor(780))

#### 11. 按照指定的axis求张量的和

In [47]:
A = torch.arange(40, dtype=torch.float32).reshape(2, 4, 5)
A_sum_axis0 = A.sum(axis = 0)
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.]],
 
         [[20., 21., 22., 23., 24.],
          [25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34.],
          [35., 36., 37., 38., 39.]]]),
 tensor([[20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.],
         [40., 42., 44., 46., 48.],
         [50., 52., 54., 56., 58.]]),
 torch.Size([4, 5]))

In [43]:
A_sum_axis1 = A.sum(axis = 1)
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]],
 
         [[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]),
 tensor([[ 30,  34,  38,  42,  46],
         [110, 114, 118, 122, 126]]),
 torch.Size([2, 5]))

In [38]:
A_sum_axis2 = A.sum(axis = 2)
A, A_sum_axis2, A_sum_axis2.shape

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]],
 
         [[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]),
 tensor([[ 10,  35,  60,  85],
         [110, 135, 160, 185]]),
 torch.Size([2, 4]))

In [40]:
A.sum(axis=[0, 1]), A.sum(axis=[0, 1]).shape

(tensor([140, 148, 156, 164, 172]), torch.Size([5]))

#### 12.求平均数

In [48]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [50]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]))

#### 13. 计算数值时，保持轴数不变

In [55]:
A = torch.arange(40).reshape(2, 4, 5)
sum_A = A.sum(axis = 1, keepdims=True) ## 用来搞广播机制的
A, sum_A

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]],
 
         [[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]),
 tensor([[[ 30,  34,  38,  42,  46]],
 
         [[110, 114, 118, 122, 126]]]))

In [54]:
A / sum_A

tensor([[[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
         [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
         [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
         [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]],

        [[0.1818, 0.1842, 0.1864, 0.1885, 0.1905],
         [0.2273, 0.2281, 0.2288, 0.2295, 0.2302],
         [0.2727, 0.2719, 0.2712, 0.2705, 0.2698],
         [0.3182, 0.3158, 0.3136, 0.3115, 0.3095]]])

In [56]:
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 22, 24, 26, 28],
         [30, 32, 34, 36, 38],
         [40, 42, 44, 46, 48],
         [50, 52, 54, 56, 58]]])

#### 14.点积运算

In [58]:
x = torch.ones(4, dtype=torch.float32)
y = torch.rand(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([1., 1., 1., 1.]),
 tensor([0.3142, 0.5129, 0.6167, 0.1609]),
 tensor(1.6047))

In [60]:
torch.sum(x * y) ### 等价于 torch.dot(x, y)

tensor(1.6047)

#### 15. 矩阵与向量相乘($\mathbf{Ax}$)可以得到一个长度维m的列向量
#### 得到的每一维的标量是矩阵的行向量$\alpha_i^T$和$\mathbf{x}$的点积，即$\alpha_i^T\mathbf{x}$
#### torch.mv()表示matrix_vector_multiplication

In [63]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 6., 22., 38., 54., 70.]))

#### 16. $\mathbf{L}_2$范数表示向量所有元素平方求和后开根号:$$\mathbf{||x||_2}=\sqrt{\sum_{i=1}^n{x_i^2}}$$

In [64]:
u = torch.tensor([3.0, 4])
torch.norm(u)

tensor(5.)

#### 17. $\mathbf{L_1}$范数定义为向量的所有元素加上绝对值后求和：$$\mathbf{||x||_1}=\sum_{i=1}^n{|x_i|}$$

In [65]:
torch.abs(u).sum()

tensor(7.)

#### 18. 矩阵的Frobenius norm是矩阵元素的平方和的平方根：
#### $$\mathbf{||X||_F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^n{x_{ij}^2}}$$

In [79]:
X = torch.arange(40, dtype=torch.float32).reshape((2, 4, 5))
X.norm(), (X*X).sum().sqrt()

(tensor(143.3178), tensor(143.3178))